In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

## Q1.  yes, there is a difference in the data type of variables list_ and array_list

In [6]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

## Q2.  code

In [9]:
import numpy as np

print('Array:', list_)
 
print('Datatype:', type(list_))

print('Array:', array_list)
 
print('Datatype:', type(array_list))

Array: ['1', '2', '3', '4', '5']
Datatype: <class 'list'>
Array: ['1' '2' '3' '4' '5']
Datatype: <class 'numpy.ndarray'>


## Q3.  code

In [10]:
new_array_list = np.array(object = list_, dtype = int)
new_array_list

array([1, 2, 3, 4, 5])

In [11]:
type(new_array_list)

numpy.ndarray

### there is no difference in the data type of the elements present in both the variables, list_ and new_array_list

## Q4.  code

In [1]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [2]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.shape(num_array)

(2, 3)

In [6]:
np.size(num_array)

6

## Q5.  code

In [10]:
import numpy as np
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Q6.  code

In [17]:
import numpy as np

dimension = int(input("Enter the dimension of identitiy matrix: "))
identity_matrix = np.identity(dimension , dtype='int')
print(identity_matrix)

Enter the dimension of identitiy matrix:  5


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
